# Windows / WPF: generate all application icon resources from the SVG master.
param([switch]$Check)
$ErrorActionPreference = 'Stop'
$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$assets = Join-Path $repoRoot 'desktop/AirFlash.App/Assets'
foreach ($assembly in @('WindowsBase', 'PresentationCore', 'PresentationFramework')) { Add-Type -AssemblyName $assembly }

[xml]$svg = Get-Content -LiteralPath (Join-Path $assets 'app.svg') -Raw
if ($svg.DocumentElement.GetAttribute('viewBox') -ne '0 0 64 64') { throw 'Expected a 64-unit SVG viewBox.' }
# This master uses only filled paths and optional solid strokes. Reject unsupported
# SVG features instead of silently generating a different image from the browser.
$lines = [Collections.Generic.List[string]]::new()
$lines.Add('<!-- Generated by scripts/generate-icons.ps1 from app.svg. Do not edit. -->')
$lines.Add('<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">')
$lines.Add('  <DrawingImage x:Key="AppLogo">')
$lines.Add('    <DrawingImage.Drawing>')
$lines.Add('      <DrawingGroup>')
$lines.Add('        <GeometryDrawing Brush="Transparent" Geometry="M 0,0 H 64 V 64 H 0 Z"/>')
foreach ($element in $svg.DocumentElement.ChildNodes) {
    if ($element.NodeType -ne [Xml.XmlNodeType]::Element -or $element.LocalName -eq 'title') { continue }
    if ($element.LocalName -ne 'path') { throw "Unsupported SVG element: $($element.LocalName)" }
    foreach ($attribute in $element.Attributes) {
        if ($attribute.Name -notin @('fill', 'stroke', 'stroke-width', 'd')) { throw "Unsupported SVG attribute: $($attribute.Name)" }
    }
    $path = [Security.SecurityElement]::Escape($element.GetAttribute('d'))
    $fill = $element.GetAttribute('fill')
    if ($fill -eq 'none') { $fill = '{x:Null}' }
    elseif ($fill -notmatch '^#[0-9A-Fa-f]{6}$') { throw 'Paths must specify a solid fill or none.' }
    if ($element.HasAttribute('stroke')) {
        $stroke = $element.GetAttribute('stroke')
        $thickness = $element.GetAttribute('stroke-width')
        if ($stroke -notmatch '^#[0-9A-Fa-f]{6}$' -or $thickness -notmatch '^\d+(\.\d+)?$') { throw 'Expected a solid stroke and numeric width.' }
        $lines.Add("        <GeometryDrawing Brush=`"$fill`" Geometry=`"$path`">")
        $lines.Add("          <GeometryDrawing.Pen><Pen Brush=`"$stroke`" Thickness=`"$thickness`" StartLineCap=`"Flat`" EndLineCap=`"Flat`"/></GeometryDrawing.Pen>")
        $lines.Add('        </GeometryDrawing>')
    }
    else { $lines.Add("        <GeometryDrawing Brush=`"$fill`" Geometry=`"$path`"/>") }
}
$lines.Add('      </DrawingGroup>')
$lines.Add('    </DrawingImage.Drawing>')
$lines.Add('  </DrawingImage>')
$lines.Add('</ResourceDictionary>')
$xaml = ($lines -join "`n") + "`n"
$dictionary = [Windows.Markup.XamlReader]::Parse($xaml)
$drawing = $dictionary['AppLogo'].Drawing
$drawing.Freeze()

function Get-LogoPng([int]$Size) {
    $visual = [Windows.Media.DrawingVisual]::new()
    $context = $visual.RenderOpen()
    $context.PushTransform([Windows.Media.ScaleTransform]::new($Size / 64.0, $Size / 64.0))
    $context.DrawDrawing($drawing)
    $context.Pop()
    $context.Close()
    $bitmap = [Windows.Media.Imaging.RenderTargetBitmap]::new($Size, $Size, 96, 96, [Windows.Media.PixelFormats]::Pbgra32)
    $bitmap.Render($visual)
    $encoder = [Windows.Media.Imaging.PngBitmapEncoder]::new()
    $encoder.Frames.Add([Windows.Media.Imaging.BitmapFrame]::Create($bitmap))
    $stream = [IO.MemoryStream]::new()
    try { $encoder.Save($stream); return ,$stream.ToArray() } finally { $stream.Dispose() }
}

$sizes = @(16,20,24,28,32,40,48,56,60,64,72,80,96,128,192,256)
$frames = @($sizes | ForEach-Object { ,(Get-LogoPng $_) })
$icoStream = [IO.MemoryStream]::new()
$writer = [IO.BinaryWriter]::new($icoStream)
try {
    $writer.Write([uint16]0); $writer.Write([uint16]1); $writer.Write([uint16]$sizes.Count)
    $offset = 6 + 16 * $sizes.Count
    for ($i = 0; $i -lt $sizes.Count; $i++) {
        $dimension = if ($sizes[$i] -eq 256) { 0 } else { $sizes[$i] }
        $writer.Write([byte]$dimension); $writer.Write([byte]$dimension)
        $writer.Write([byte]0); $writer.Write([byte]0)
        $writer.Write([uint16]1); $writer.Write([uint16]32)
        $writer.Write([uint32]$frames[$i].Length); $writer.Write([uint32]$offset)
        $offset += $frames[$i].Length
    }
    foreach ($frame in $frames) { $writer.Write([byte[]]$frame) }
    $outputs = [ordered]@{
        'app.xaml' = [Text.UTF8Encoding]::new($false).GetBytes($xaml)
        'app.png' = Get-LogoPng 512
        'app.ico' = $icoStream.ToArray()
    }
} finally { $writer.Dispose(); $icoStream.Dispose() }

foreach ($name in $outputs.Keys) {
    $path = Join-Path $assets $name
    if ($Check) {
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "Missing generated icon: $name" }
        $expected = [Convert]::ToHexString([Security.Cryptography.SHA256]::HashData($outputs[$name]))
        if ((Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash -ne $expected) { throw "Stale icon: $name. Run pwsh -STA -File scripts/generate-icons.ps1." }
    }
    else { [IO.File]::WriteAllBytes($path, $outputs[$name]) }
}
# Validate the container's frame dimensions, alpha and decodeability as well.
$inputStream = [IO.MemoryStream]::new([byte[]]$outputs['app.ico'])
try {
    $decoder = [Windows.Media.Imaging.IconBitmapDecoder]::new($inputStream, [Windows.Media.Imaging.BitmapCreateOptions]::PreservePixelFormat, [Windows.Media.Imaging.BitmapCacheOption]::OnLoad)
    if ($decoder.Frames.Count -ne $sizes.Count) { throw 'ICO frame count mismatch.' }
    for ($i = 0; $i -lt $sizes.Count; $i++) {
        $frame = $decoder.Frames[$i]
        if ($frame.PixelWidth -ne $sizes[$i] -or $frame.PixelHeight -ne $sizes[$i]) { throw 'ICO frame size mismatch.' }
        $converted = [Windows.Media.Imaging.FormatConvertedBitmap]::new($frame, [Windows.Media.PixelFormats]::Bgra32, $null, 0)
        $pixels = [byte[]]::new($sizes[$i] * $sizes[$i] * 4)
        $converted.CopyPixels($pixels, $sizes[$i] * 4, 0)
        if ($pixels[3] -ne 0 -or $pixels[($sizes[$i] * [int]($sizes[$i]/2) + [int]($sizes[$i]/2)) * 4 + 3] -ne 255) { throw 'ICO transparency mismatch.' }
    }
} finally { $inputStream.Dispose() }
Write-Output "Icons $(if ($Check) { 'verified' } else { 'generated' }): SVG -> WPF, 512px PNG, $($sizes.Count) ICO frames."
